export type BlogCategory = 'expats' | 'profissionais'

export interface BlogArticle {
  slug: string
  title: string
  excerpt: string
  category: BlogCategory
  date: string
  readTime: string
  coverImage: string
  content: string[]
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: 'lidando-com-saudade-saude-mental',
    title: 'Como lidar com a saudade de casa sem deixar sua saúde mental de lado',
    excerpt:
      'A saudade bate diferente quando você está a milhares de quilômetros. Aprenda a reconhecer os sinais e cuidar de si mesmo sem culpa.',
    category: 'expats',
    date: '15 de abril de 2026',
    readTime: '8 min',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    content: [
      'Quando eu mudei para Portugal, achava que a saudade seria algo passageiro. Tipo uma gripe: incomoda por alguns dias, mas depois você se acostuma. Só que ninguém me avisou que a saudade não some. Ela muda de formato. Às vezes é o cheiro do café passando na padaria da esquina. Às vezes é uma música que toca no Spotify e você para no meio da rua. Às vezes é só o silêncio da noite, quando você percebe que não tem ninguém para ligar às três da manhã.',
      'E está tudo bem. Está tudo bem sentir isso. O problema começa quando a gente tenta enterrar a saudade achando que isso é sinal de fraqueza. Não é. É sinal de que você ama algo. E amar é sempre uma força, nunca uma fraqueza.',
      '<h2>O que a ciência diz sobre saudade</h2>',
      'Pesquisadores da Universidade de Southampton definiram saudade como um sentimento complexo que mistura tristeza, nostalgia e desejo de conexão. O interessante é que a saudade não é só sobre lugares — é sobre pessoas, rotinas, sensações, até sobre uma versão sua que existia em determinado contexto.',
      'Quando moramos fora, a saudade ganha camadas extras: a frustração de não conseguir explicar para os locais o que você está sentindo, a solidão de celebrar conquistas sozinho, o cansaço de ter que traduzir não só palavras, mas emoções.',
      '<h2>Sinais de que a saudade está pedindo ajuda</h2>',
      'É normal sentir falta de casa. Mas preste atenção quando a saudade começar a interferir no seu dia a dia:',
      '<ul><li>Você dorme mal há semanas e não sabe explicar por quê</li><li>Perdeu o interesse por atividades que costumava gostar</li><li>Isola-se dos amigos novos que fez no país</li><li>Sente culpa constante por estar longe da família</li><li>Tem dificuldade de se concentrar no trabalho ou estudos</li></ul>',
      'Esses sinais não significam que você tomou a decisão errada de sair do Brasil. Significam que você está humano e precisa de apoio. E buscar ajuda não é desistir — é cuidar de si para poder continuar.',
      '<h2>Estratégias que realmente funcionam</h2>',
      '<h3>Crie rituais de conexão</h3>',
      'Não espere ter saudade para ligar para casa. Agende videochamadas regulares, mas também deixe espaço para o espontâneo: mande uma foto do pôr do sol, um áudio contando algo engraçado que aconteceu, um vídeo de 10 segundos do seu café da manhã. A conexão não precisa ser profunda para ser real.',
      '<h3>Construa uma vida onde você está</h3>',
      'A saudade fica mais dócil quando você tem coisas que ama no presente. Encontre um café favorito, uma trilha, um grupo de corrida, uma aula de algo novo. Você não está traindo o Brasil por gostar de viver onde está.',
      '<h3>Fale com quem entende</h3>',
      'Amigos locais são ótimos, mas às vezes você precisa de alguém que entenda o contexto brasileiro sem você precisar explicar. Terapia com um psicólogo que fala português e conhece a realidade de viver fora faz uma diferença enorme. Você economiza metade da sessão só em traduzir cultura.',
      '<h3>Permita-se sentir</h3>',
      'O pior que você pode fazer é se cobrar para "já estar adaptado". Adaptação não tem prazo de validade. Tem dias que você vai sentir que pertence ao lugar. Tem dias que tudo vai parecer estranho. Os dois são válidos.',
      '<h2>Você não está sozinho nisso</h2>',
      'Mais de cinco milhões de brasileiros vivem fora do país. Cada um deles já chorou de saudade em algum momento. Cada um deles já duvidou se fez a escolha certa. E cada um deles, de uma forma ou de outra, encontrou um jeito de seguir.',
      'A saudade não é um defeito. É prova de que você veio de algum lugar que merecia ser amado. E amar de longe também é uma forma de estar presente.',
    ],
  },
  {
    slug: 'como-encontrar-psicologo-brasileiro-exterior',
    title: 'Guia prático: como encontrar um psicólogo brasileiro quando você mora no exterior',
    excerpt:
      'Procurar ajuda psicológica em outro idioma é como tentar descrever uma cor que não existe no vocabulário local. Veja como resolver isso.',
    category: 'expats',
    date: '10 de abril de 2026',
    readTime: '7 min',
    coverImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&q=80',
    content: [
      'Eu lembro da primeira vez que procurei um psicólogo em Londres. Senti na pele o que é tentar explicar o conceito de "saudade" para alguém que nunca sentiu falta de um lugar daquele jeito. É como tentar traduzir poesia: as palavras existem, mas o peso não.',
      'A terapia já é um espaço de vulnerabilidade. Quando você ainda precisa traduzir emoções, metáforas e contextos culturais, fica mais difícil ainda. E não é sobre o psicólogo ser bom ou ruim — é sobre a barreira invisível que o idioma e a cultura criam.',
      '<h2>Por que um psicólogo brasileiro faz diferença</h2>',
      'Não se trata de nacionalismo. Trata-se de contexto compartilhado. Um psicólogo que conhece a cultura brasileira entende coisas que nem você consegue explicar: o peso do "jeitinho brasileiro", a complexidade das relações familiares estendidas, a vergonha de falar de dinheiro, a culpa de estar longe.',
      'Você não precisa perder 20 minutos de uma sessão de 50 explicando por que o natal brasileiro é diferente, ou por que você se sente culpado por não mandar dinheiro para casa, ou por que a palavra "saudade" carrega tanto. Ele já sabe.',
      '<h2>O que procurar em um profissional online</h2>',
      '<h3>Especialização em expatriados</h3>',
      'Nem todo psicólogo brasileiro entende a realidade de quem mora fora. Procure alguém que mencione experiência com expatriados, imigrantes ou brasileiros no exterior. A dinâmica é diferente e requer abordagens específicas.',
      '<h3>Abordagem terapêutica compatível</h3>',
      'CBT, psicanálise, gestalt, ACT — cada abordagem tem seus méritos. O importante é que você se sinta confortável. A primeira sessão é uma entrevista mútua: você avalia o profissional tanto quanto ele avalia você.',
      '<h3>Flexibilidade de horários</h3>',
      'Fuso horário é real. Um profissional que atende online precisa ter horários que funcionem para você, não só para quem está no Brasil. Verifique se ele tem experiência com clientes em diferentes fusos.',
      '<h2>Como a plataforma resolve isso</h2>',
      'A Muuday nasceu justamente dessa dor. Em vez de você ter que procurar em dez sites diferentes, explicar sua situação dez vezes e torcer para encontrar alguém disponível no seu horário, a plataforma reúne profissionais brasileiros que já atendem online e já entendem seu contexto.',
      'Você filtra por especialidade, vê avaliações de outros brasileiros no exterior, agenda no seu fuso e faz a sessão por videochamada integrada. Sem precisar explicar o Brasil para ninguém.',
      '<h2>A primeira sessão: o que esperar</h2>',
      'A primeira sessão geralmente é uma conversa mais ampla. O psicólogo vai querer entender sua história, por que você está buscando ajuda agora, como está sua rotina no país onde mora. Não há pressa. Não há julgamento.',
      'É normal sentir nervosismo antes. É normal também não sentir "química" com o primeiro profissional que você procura. A terapia é uma relação, e relações precisam de afinidade. Se não rolou, procure outro. Não desista do processo.',
      '<h2>Você merece ser ouvido na sua língua</h2>',
      'A decisão de cuidar da sua saúde mental já é um ato de coragem. Não deixe que a barreira do idioma seja mais um obstáculo. Você merece um espaço onde possa ser completamente você — sem traduções, sem simplificações, sem desculpas.',
    ],
  },
  {
    slug: 'impostos-documentos-burocracia-exterior',
    title: 'Impostos, documentos e burocracia: o que ninguém te conta antes de sair do Brasil',
    excerpt:
      'O sonho de morar fora vem com uma pasta de papelada que ninguém avisou. Um guia honesto sobre o que você realmente precisa organizar.',
    category: 'expats',
    date: '5 de abril de 2026',
    readTime: '10 min',
    coverImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80',
    content: [
      'Quando eu decidi sair do Brasil, me preocupei com passagem, visto e apartamento. O que eu não sabia é que esses são só os primeiros três itens de uma lista que nunca acaba. Imposto de renda nos dois países. Declaração de saída definitiva. Transferência de dinheiro. Reconhecimento de diploma. Seguro saúde. Conta bancária sem histórico de crédito. E a lista continua.',
      'Ninguém te conta porque, de certa forma, é impossível contar tudo. Cada país tem suas regras. Cada estado ou província tem variações. E as regras mudam. Mas existem algumas verdades universais que todo brasileiro no exterior enfrenta.',
      '<h2>Impostos: você não escapa, só muda de endereço</h2>',
      'O Brasil tem acordos de reciprocidade tributária com vários países, mas isso não significa que você não precisa declarar nada. Se você ainda tem CNPJ, recebe aluguel, tem investimentos ou recebe herança no Brasil, as obrigações continuam.',
      'A regra geral é: você precisa declarar imposto de renda no Brasil se tiver rendimentos de fonte brasileira, mesmo morando fora. E no país onde reside, depende das regras locais. A boa notícia é que, em muitos casos, você não paga duas vezes — mas precisa declarar nas duas.',
      '<h2>Documentos: quanto antes, melhor</h2>',
      '<ul><li><strong>Certidão de nascimento e casamento</strong>: tire várias cópias autenticadas antes de sair. Apostilamento (Haia) é essencial para países signatários</li><li><strong>Diplomas e históricos</strong>: reconhecimento internacional leva meses. Comece o processo antes de emigrar</li><li><strong>Carteira de motorista</strong>: alguns países permitem troca direta, outros exigem prova do zero</li><li><strong>CPF regularizado</strong>: mantenha atualizado no Brasil. Você vai precisar mais vezes do que imagina</li></ul>',
      '<h2>Dinheiro: transferir não é simples</h2>',
      'Wise, Remitly, Western Union — existem várias opções, mas cada uma tem limites, taxas e prazos. Para valores maiores, você pode precisar de documentação comprobatória. E cuidado com as oscilações cambiais: o que parece bom hoje pode não ser amanhã.',
      '<h2>Seguro saúde: leia a letra miúda</h2>',
      'Seguros costumam ter período de carência, exclusões para condições pré-existentes e limites que você só descobre quando precisa. Em países com sistema público, entenda como funciona o acesso para estrangeiros — nem todo lugar é igual ao SUS.',
      '<h2>A verdade que ninguém conta</h2>',
      'Você vai errar. Vai pagar taxa que não precisava. Vai perder prazo. Vai se frustrar com atendimento que não resolve nada. Isso é normal. Todo mundo passa por isso.',
      'O que separa quem desiste de quem fica é a paciência de entender que burocracia é uma habilidade que se desenvolve. Você não nasceu sabendo como funciona a Receita Federal brasileira, então também não vai nascer sabendo como funciona a de outro país.',
      '<h2>Profissionais que podem ajudar</h2>',
      'Não tente fazer tudo sozinho. Contadores brasileiros que entendem de expatriados, advogados especializados em imigração, consultores de investimento — existem profissionais que já passaram por isso e podem te poupar tempo, dinheiro e dor de cabeça.',
      'A Muuday reúne alguns desses profissionais. Não porque eles são mágicos, mas porque eles já entendem o seu ponto de partida. E isso economiza metade da explicação.',
    ],
  },
  {
    slug: 'manter-relacionamentos-distancia',
    title: 'Como manter relacionamentos à distância sem enlouquecer',
    excerpt:
      'Namoro, casamento, amizade, família — a distância testa todos os tipos de laço. Veja como nutrir conexões reais mesmo a quilômetros de distância.',
    category: 'expats',
    date: '28 de março de 2026',
    readTime: '8 min',
    coverImage: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=1200&q=80',
    content: [
      'Tem uma frase que eu ouvi logo que cheguei em Portugal e nunca esqueci: "A distância não separa pessoas. O silêncio sim." Na época, achei bonita demais para ser verdade. Hoje, depois de três anos fora, sei que é só metade da verdade. A distância separa sim. Ela separa presenças, rotinas, experiências compartilhadas. Mas o silêncio é o que mata.',
      'Manter um relacionamento à distância — seja romântico, familiar ou de amizade — exige uma recalibragem completa de como você se conecta. Não adianta tentar replicar o que funcionava quando vocês moravam na mesma cidade. Você precisa inventar algo novo.',
      '<h2>A ilusão da comunicação constante</h2>',
      'Muita gente acha que relacionamento à distância significa mensagem o dia todo, ligação toda noite, compartilhamento de localização. Erro. Comunicação excessiva pode ser tão danosa quanto o silêncio. Cria uma sensação de obrigação, de dever cumprido, de performance.',
      'O segredo não é quantidade. É qualidade. Uma conversa de 20 minutos onde você realmente escuta vale mais que 200 mensagens de "bom dia" e "boa noite".',
      '<h2>Práticas que fortalecem</h2>',
      '<h3>Crie rituais, não rotinas</h3>',
      'Rotina cansa. Ritual conecta. A diferença é a intenção. Assistir ao mesmo episódio de uma série "juntos" por videochamada é um ritual. Marcar uma videochamada toda terça às 20h porque "tem que ser" é uma rotina. Rituais têm significado. Rotinas têm obrigação.',
      '<h3>Compartilhe o mundano</h3>',
      'A tentação é só contar as grandes coisas. Mas relacionamentos são feitos de detalhes pequenos. Mande uma foto do seu café, do céu estranho que você viu, do gato do vizinho. O ordinário é o que constrói intimidade.',
      '<h3>Seja honesto sobre o que é difícil</h3>',
      'Não finja que está tudo bem se não está. Dizer "estou com saudade e hoje está doendo mais" não é fraqueza — é confiança. Quando você permite que a outra pessoa veja sua vulnerabilidade, você dá permissão para que ela também mostre a dela.',
      '<h3>Planeje encontros, mesmo que distantes</h3>',
      'Ter uma data na agenda muda a psicologia da distância. Mesmo que seja daqui a seis meses, saber que vocês vão se ver cria um horizonte. E horizontes são psicologicamente essenciais para quem está longe.',
      '<h2>Quando a distância revela incompatibilidades</h2>',
      'Vou ser honesto: nem todo relacionamento sobrevive à distância. E isso não é necessariamente uma tragédia. Às vezes, a distância não destrói — ela revela. Revela que vocês já não estavam tão conectados quanto imaginavam. Revela que cresceram em direções diferentes.',
      'Se isso acontecer, tente não ver como fracasso. A distância foi um teste, e o teste mostrou um resultado. Resultados não são bons ou maus — são informações.',
      '<h2>Você não precisa salvar todos os relacionamentos</h2>',
      'Tem amizade que não resiste ao fuso horário. Tem familiar que não entende por que você foi embora. Tem romance que não aguenta a ausência. E está tudo bem. Você não é obrigado a manter todos os laços que tinha no Brasil.',
      'O que importa é que os relacionamentos que você mantém sejam reais. Que a conexão exista não por inércia, mas por escolha. Que ambos os lados estejam dispostos a fazer a distância funcionar.',
      'Porque no fim das contas, a distância é só espaço. E espaço pode ser preenchido de muitas formas.',
    ],
  },
  {
    slug: 'alimentacao-exterior-saudade-comida',
    title: 'Alimentação no exterior: como não sentir falta da comida da mãe (tanto assim)',
    excerpt:
      'Arroz e feijão em Londres custam o olho da cara. Veja como se alimentar bem sem abandonar suas raízes nem quebrar o orçamento.',
    category: 'expats',
    date: '20 de março de 2026',
    readTime: '6 min',
    coverImage: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?w=1200&q=80',
    content: [
      'A primeira vez que fui em um mercado em Dublin e vi o preço do arroz carioca, quase chorei. Quatro euros por um pacote de um quilo. No Brasil, dava para comprar cinco. E o feijão preto? Nem sempre achava. Quando achava, era caríssimo e vinha enlatado com um líquido suspeito.',
      'A comida é a saudade que a gente não espera. Você se prepara para sentir falta da família, dos amigos, do clima. Mas ninguém avisa que um dia você vai acordar com uma vontade insuportável de pão de queijo e não vai ter para onde ir.',
      '<h2>A fase da negação</h2>',
      'Todo brasileiro no exterior passa por isso. Primeiro, você tenta replicar tudo exatamente igual. Leva horas procurando ingredientes em três mercados diferentes. Gasta o triplo do orçamento. O resultado nunca fica igual. E você fica frustrado.',
      'A curva de aprendizado é: negação, frustração, adaptação, hibridização. O segredo é passar rápido das duas primeiras fases.',
      '<h2>Estratégias práticas</h2>',
      '<h3>Aprenda a cozinhar o básico</h3>',
      'Se você depende de restaurantes brasileiros ou produtos importados, vai quebrar. Aprender a fazer arroz, feijão, macarrão, frango grelhado e alguns legumes no forno é sobrevivência básica. Não precisa ser MasterChef. Precisa ser funcional.',
      '<h3>Descubra os mercados locais</h3>',
      'Cada país tem seus próprios tesouros. Em Portugal, o bacalhau é acessível e versátil. Na Espanha, as tortillas e os embutidos. Na Alemanha, pães e encurtidos. Você não precisa abandonar a comida brasileira, mas adicionar opções locais reduz drasticamente a saudade.',
      '<h3>Faça rodízios com outros brasileiros</h3>',
      'Nada substitui uma feijoada feita por brasileiros, para brasileiros. Organize encontros mensais onde cada um leva um prato. Você divide o custo, multiplica a variedade e ainda constrói comunidade.',
      '<h3>Use tecnologia a seu favor</h3>',
      'Existem receitas adaptadas para ingredientes locais em praticamente todo lugar. Grupos de brasileiros no Facebook e Reddit compartilham dicas de onde encontrar produtos, substitutos e até receitas de pão de queijo com queijo local.',
      '<h2>Nutrição emocional</h2>',
      'Um nutricionista brasileiro que entende sua realidade pode ajudar muito mais do que você imagina. Não é só sobre calorias e macros — é sobre entender que comida, para brasileiros, é identidade. É sobre encontrar um equilíbrio entre cuidar da saúde e não se sentir culpado por querer um brigadeiro de vez em quando.',
      '<h2>A verdade sobre a comida da mãe</h2>',
      'Vou te contar um segredo: a comida da sua mãe nunca vai ficar igual quando você faz. E não é porque você não sabe cozinhar. É porque metade do sabor era o contexto — a casa, a mesa, a conversa, o cheiro do quintal. Você não está sentindo falta só da comida. Está sentindo falta de tudo o que vinha junto.',
      'E isso é normal. Aceite a saudade, mas não deixe que ela defina sua alimentação. Crie novas memórias ao redor da comida onde você está. Daqui a pouco, você vai ter receitas que seus amigos no Brasil vão querer aprender.',
    ],
  },
 {
    slug: 'primeira-consulta-profissional-online',
    title: 'Primeira consulta com um profissional brasileiro online: o que esperar e como se preparar',
    excerpt:
      'A primeira vez é sempre estranha. Saiba como aproveitar ao máximo sua primeira sessão online com um psicólogo, nutricionista ou outro especialista.',
    category: 'expats',
    date: '15 de março de 2026',
    readTime: '6 min',
    coverImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&q=80',
    content: [
      'Vou ser direto: a primeira sessão online é estranha. Você está na sua casa, no seu sofá, com seu pijama de baixo e uma blusa decente em cima, falando com uma pessoa que você nunca viu sobre coisas profundas. É normal sentir vergonha, ansiedade ou vontade de cancelar cinco minutos antes.',
      'Mas também vou te dizer outra coisa: depois de dez minutos, você esquece que está online. A conexão humana não depende de estar na mesma sala. Depende de atenção, empatia e vontade de estar presente. E isso, videochamada transmite perfeitamente.',
      '<h2>Como se preparar</h2>',
      '<h3>Crie um ambiente</h3>',
      'Não precisa de home office. Precisa de um canto onde você não será interrompido por 50 minutos. Avisar quem mora com você, colocar fones de ouvido, fechar a porta. O ambiente físico ajuda o ambiente mental.',
      '<h3>Teste a tecnologia antes</h3>',
      'Entre na plataforma cinco minutos antes. Verifique microfone, câmera, conexão. Nada pior que passar os primeiros dez minutos da sessão resolvendo problema técnico.',
      '<h3>Pense no que te trouxe até aqui</h3>',
      'Não precisa de script. Mas ajuda saber, de forma geral, o que você quer compartilhar. "Estou me sentindo ansioso desde que mudei", "Tenho dificuldade de dormir", "Quero entender por que me sinto culpado" — qualquer ponto de partida serve.',
      '<h2>O que acontece na sessão</h2>',
      'O profissional vai querer te conhecer. Vai perguntar sobre sua história, sua rotina, por que você decidiu buscar ajuda agora. Não há respostas certas ou erradas. Não há julgamento.',
      'A primeira sessão geralmente é mais leve do que as seguintes. É um mapeamento. O profundo vem depois, quando a confiança estiver construída.',
      '<h2>Depois da sessão</h2>',
      'É normal sentir uma mistura de alívio e exaustão. Falar de si mesmo exige energia. Dê-se espaço. Não programe reuniões importantes imediatamente depois. Tome um café, faça uma caminhada, deixe as coisas assentarem.',
      '<h2>Se não rolou química</h2>',
      'A primeira sessão é também uma entrevista mútua. Você está avaliando o profissional tanto quanto ele está avaliando você. Se você não se sentiu confortável, se algo não bateu, procure outro. Relação terapêutica precisa de afinidade.',
      'A Muuday permite que você veja avaliações de outros brasileiros e troque de profissional sem burocracia. Porque o que importa é que você encontre alguém com quem consiga ser verdadeiramente aberto.',
      '<h2>Você já deu o passo mais difícil</h2>',
      'Reconhecer que precisa de ajuda e agir em cima disso é um ato de coragem enorme. A primeira sessão é só o começo de um caminho que pode transformar completamente como você se relaciona com si mesmo e com o mundo.',
      'E lembre: não existe problema "pequeno demais" para terapia. Se algo te incomoda, merece atenção. Você merece atenção.',
    ],
  },
  {
    slug: 'transformar-expertise-carreira-global',
    title: 'Como transformar sua expertise brasileira em uma carreira global',
    excerpt:
      'Você já tem o conhecimento. O que falta é entender como vendê-lo para o mundo. Um guia direto para profissionais brasileiros no exterior.',
    category: 'profissionais',
    date: '12 de abril de 2026',
    readTime: '9 min',
    coverImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200&q=80',
    content: [
      'Quando eu me mudei para Lisboa como psicóloga, tinha dez anos de experiência clínica no Brasil. Diplomas, especializações, milhares de horas de atendimento. Achava que o desafio seria a língua. Estava errada. O desafio era entender que o mercado não me conhecia. Minha expertise era real, mas invisível.',
      'Essa é a história de praticamente todo profissional brasileiro que migra. Você chega com um currículo sólido, mas sem rede, sem referências, sem reputação local. E o mercado não tem paciência para descobrir quem você é. Você precisa mostrar.',
      '<h2>O primeiro passo: traduzir sua história</h2>',
      'Não é sobre traduzir palavras. É sobre traduzir valor. No Brasil, você era "psicóloga com dez anos de experiência". No exterior, você é "profissional de saúde mental com background multicultural". A mesma trajetória, contada para um público diferente.',
      'Pergunte a si mesmo: o que eu sei fazer que é raro aqui? Que problemas eu resolvo que os locais não resolvem tão bem? A resposta é o seu diferencial.',
      '<h2>Construa presença online antes de precisar dela</h2>',
      'LinkedIn otimizado. Site simples. Um perfil claro no Instagram ou TikTok onde você compartilha conhecimento. Não precisa ser influencer. Precisa ser encontrável.',
      'O brasileiro no exterior tem uma vantagem injusta: ele entende dois mundos. Isso é ouro para conteúdo. Você pode explicar o mercado local para brasileiros e a realidade brasileira para o mercado local. Pouca gente faz isso bem.',
      '<h2>Preço é percepção de valor</h2>',
      'A tentação inicial é cobrar menos para "conseguir clientes". Erro. Preço baixo sinaliza valor baixo. Se você cobra metade do mercado, o cliente assume que você vale metade.',
      'Comece com preço justo — nem abaixo nem acima do mercado — e aumente conforme sua demanda cresce. Clientes que valorizam qualidade pagam por qualidade. Clientes que só olham preço não são seus clientes.',
      '<h2>A plataforma como ponte</h2>',
      'Vender serviços online exige infraestrutura: site, agenda, pagamento, videochamada, lembretes. Construir isso sozinho leva meses e custa caro.',
      'A Muuday existe para resolver isso. Você cria seu perfil, define seus serviços e preços, e a plataforma cuida do resto. Os clientes brasileiros já estão lá procurando exatamente pelo que você oferece. Você só precisa aparecer.',
      '<h2>Paciência é parte da estratégia</h2>',
      'Os primeiros clientes são os mais difíceis. Você ainda não tem avaliações, ainda não tem reputação, ainda não tem indicação. Mas cada cliente bem atendido se multiplica. Cada sessão é uma semente.',
      'A regra é simples: entregue tão bem que o cliente não consiga deixar de indicar você. E quando indicar, facilite: tenha um perfil profissional, um link de agendamento, um processo simples. Quanto menos atrito, mais indicações.',
      '<h2>Você já tem tudo que precisa</h2>',
      'O conhecimento. A experiência. A vontade. O que falta é só o canal. E canais podem ser construídos. O mundo está mais conectado do que nunca, e brasileiros no exterior precisam de você. Não subestime o valor de ser compreendido.',
    ],
  },
  {
    slug: 'guia-profissional-atender-online-exterior',
    title: 'O guia completo do profissional brasileiro que quer atender online do exterior',
    excerpt:
      'Do diploma à primeira sessão: tudo que você precisa saber para construir um consultório virtual que funcione de qualquer lugar do mundo.',
    category: 'profissionais',
    date: '8 de abril de 2026',
    readTime: '10 min',
    coverImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&q=80',
    content: [
      'Quando eu decidi que ia atender online a partir de Portugal, a primeira pergunta foi: "Isso é legal?" A segunda: "E se o cliente estiver no Brasil e eu aqui?" A terceira: "Como recebo o dinheiro?" E a lista foi crescendo.',
      'A boa notícia é: atender online do exterior é perfeitamente viável. A má notícia é: ninguém te dá um manual. Então eu escrevi um.',
      '<h2>Regularização: o básico que você não pode pular</h2>',
      '<h3>Seu diploma vale?</h3>',
      'Depende do país onde você reside e da profissão. Psicólogos, por exemplo, costumam precisar de revalidação ou registro no conselho local para atender residentes daquele país. Mas atender brasileiros no exterior ou no Brasil geralmente não exige revalidação — você está exercendo para o seu público de origem.',
      'Consulte o conselho de sua categoria no Brasil e verifique as regras do país onde reside. Cada caso é um caso.',
      '<h3>Nota fiscal e impostos</h3>',
      'Você pode emitir nota fiscal no Brasil mesmo morando fora, através de CNPJ MEI ou outra modalidade. O imposto de renda deve ser declarado no Brasil (se tiver rendimentos de fonte brasileira) e possivelmente no país de residência. Um contador brasileiro que entenda de expatriados é essencial.',
      '<h2>A infraestrutura do consultório virtual</h2>',
      '<h3>Espaço físico</h3>',
      'Você precisa de um canto silencioso, com boa iluminação e fundo profissional. Não precisa de home office completo. Uma parede limpa, uma luz natural ou um ring light, e fones de ouvido com microfone decente já resolvem.',
      '<h3>Conexão estável</h3>',
      'Investir em internet de qualidade é investir no seu negócio. Nada destrói credibilidade como cair da chamada no meio de uma sessão. Tenha um plano B (dados móveis) para emergências.',
      '<h3>Ferramentas</h3>',
      'Você precisa de: agenda online, sistema de pagamento, plataforma de videochamada, e alguma forma de lembrete automático para clientes. Montar isso sozinho exige integrar Google Calendar, Stripe, Zoom, email marketing — é possível, mas consome tempo que você poderia usar atendendo.',
      '<h2>Marketing para brasileiros no exterior</h2>',
      'Seu público não é "qualquer um". É brasileiro, no exterior, com uma necessidade específica. Fale a língua deles — não só o português, mas a cultura. Entenda que "saudade" não é só uma palavra. Que "jeitinho brasileiro" não é só um estereótipo. Que a culpa de estar longe é real.',
      'Conteúdo que funciona: "Como lidar com ansiedade sendo expatriado", "Diferenças culturais no ambiente de trabalho", "Como manter relacionamentos à distância". Eduque seu público e eles vão te procurar quando precisarem.',
      '<h2>Precificação no mercado global</h2>',
      'Pesquise quanto profissionais equivalentes cobram nos principais países onde seus clientes estão. Não copie — use como referência. Considere sua experiência, suas especializações, e o valor que você entrega.',
      'Lembre: você não está competindo por preço. Você está competindo por confiança. Clientes pagam mais por quem entende exatamente o que eles precisam.',
      '<h2>O caminho mais curto</h2>',
      'Tudo o que eu descrevi acima — agenda, pagamento, videochamada, perfil público, lembretes, avaliações — é exatamente o que a Muuday oferece. A plataforma foi construída por e para brasileiros no exterior, entendendo as nuances que plataformas genéricas ignoram.',
      'Você pode gastar meses montando sua própria infraestrutura. Ou pode criar seu perfil em uma tarde e começar a atender na semana que vem. O conhecimento você já tem. O canal é o que falta.',
    ],
  },
  {
    slug: 'como-precificar-servicos-cliente-outro-pais',
    title: 'Como precificar seus serviços quando seu cliente está em outro país',
    excerpt:
      'Dólar, euro, real, libra — como cobrar de alguém que ganha em outra moeda sem se perder no câmbio?',
    category: 'profissionais',
    date: '2 de abril de 2026',
    readTime: '7 min',
    coverImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&q=80',
    content: [
      'A primeira vez que um cliente me perguntou "você cobra em euro ou em real?", eu travei. Parecia uma pergunta simples, mas abria um labirinto: qual moeda? Qual conversão? Quando? Qual taxa? Quem paga a spread do banco?',
      'Precificar para clientes internacionais não é só definir um número. É definir um número, uma moeda, uma forma de pagamento, uma política de cancelamento, e uma forma de comunicar tudo isso de modo que o cliente entenda sem precisar de calculadora.',
      '<h2>A regra de ouro: cobre na moeda do seu custo de vida</h2>',
      'Se você mora em Portugal, seus custos estão em euros. Se você cobra em reais e o real desvaloriza, seu poder de compra cai. Cobrar na moeda do país onde você reside protege você da volatilidade cambial.',
      'A exceção: se seu público principal está em um país específico e você quer simplificar, pode cobrar na moeda deles. Mas estabeleça uma taxa de referência e revise periodicamente.',
      '<h2>Como comunicar o preço</h2>',
      'Não diga "R$ 200, o que dá mais ou menos € 37". Isso cria confusão. Diga "€ 37 por sessão" (ou qual for sua moeda base) e pronto. Se a plataforma converte automaticamente para o cliente, melhor ainda.',
      'Clareza gera confiança. Confiança gera conversão. Conversão gera receita. A matemática é simples, mas muitos profissionais perdem clientes na fase de explicar o preço.',
      '<h2>Formas de pagamento</h2>',
      '<ul><li><strong>Transferência bancária internacional</strong>: funciona, mas é lenta e cara. Evite para valores pequenos</li><li><strong>PayPal</strong>: prático, mas taxas altas (cerca de 5-6%)</li><li><strong>Wise (TransferWise)</strong>: boa para receber em conta local, taxas menores</li><li><strong>Cartão de crédito via plataforma</strong>: o mais simples para o cliente. A plataforma cuida da conversão e você recebe na sua moeda</li></ul>',
      'A experiência do cliente importa. Quanto mais fácil for pagar, mais clientes você converte. Um processo de pagamento complicado é um funil vazando.',
      '<h2>O fator psicológico da moeda</h2>',
      'R$ 200 pode parecer caro para um brasileiro no Brasil, mas razoável para um brasileiro em Londres que ganha em libras. € 50 pode parecer acessível para um europeu, mas salgado para um brasileiro em Portugal que ainda não se estabilizou.',
      'Conheça seu público. Se você atende principalmente brasileiros recém-chegados em Portugal, talvez precise ser mais flexível. Se atende brasileiros há anos em Londres, pode cobrar em libras sem problema.',
      '<h2>Pacotes e recorrência</h2>',
      'Sessões avulsas são mais fáceis de vender, mas pacotes são mais previsíveis para sua renda. Uma opção é oferecer ambos: preço avulso e desconto para pacote de 4 ou 8 sessões. Isso dá escolha ao cliente e previsibilidade para você.',
      '<h2>A plataforma resolve a matemática</h2>',
      'Na Muuday, você define seu preço em reais e o cliente paga na moeda dele. A conversão é automática. O pagamento é processado. Você recebe na sua conta. Não precisa entender de câmbio, não precisa explicar taxas, não precisa cobrar de cada um manualmente.',
      'Você se concentra no que sabe fazer: atender. A plataforma cuida do resto.',
    ],
  },
  {
    slug: 'profissionais-brasileiros-consultorios-virtuais',
    title: 'De Lisboa a Tóquio: como profissionais brasileiros estão construindo consultórios virtuais',
    excerpt:
      'Histórias reais de brasileiros que transformaram suas carreiras em negócios globais sem sair de casa.',
    category: 'profissionais',
    date: '25 de março de 2026',
    readTime: '8 min',
    coverImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&q=80',
    content: [
      'A Dra. Fernanda atende de Lisboa para clientes em Londres, Dublin e Berlim. O Dr. Ricardo, nutricionista em Londres, tem pacientes em Portugal, Espanha e até no Brasil. A advogada Carolina, morando em Berlim, orienta brasileiros em quatro países diferentes sobre regularização na União Europeia.',
      'Eles não são exceções. São parte de uma onda silenciosa de profissionais brasileiros que descobriram que a distância física não precisa ser barreira. Que expertise brasileira tem valor global. Que o mundo está mais conectado do que nunca — e eles estão usando isso a seu favor.',
      '<h2>O modelo que está funcionando</h2>',
      'O consultório virtual não é uma versão piorada do presencial. É um modelo diferente, com vantagens próprias:',
      '<ul><li><strong>Sem limites geográficos</strong>: você atende clientes em qualquer lugar com internet</li><li><strong>Sem custo fixo</strong>: não paga aluguel de sala, não gasta com transporte</li><li><strong>Horário flexível</strong>: atenda no fuso que funciona para você e para seus clientes</li><li><strong>Escalabilidade</strong>: pode atender mais clientes porque elimina o tempo de deslocamento</li></ul>',
      '<h2>Os desafios reais</h2>',
      'Nem tudo são flores. Construir presença online exige tempo. Os primeiros clientes são os mais difíceis de conseguir. A concorrência existe. E nem todo cliente se adapta bem ao formato virtual — alguns precisam de contato presencial.',
      'O segredo é saber para quem você atende. Não tente ser para todo mundo. Seja o melhor para um grupo específico. Brasileiros no exterior que precisam de apoio em português é um nicho enorme e pouco explorado.',
      '<h2>O que diferencia quem cresce</h2>',
      'Profissionais que constroem reputação online têm três coisas em comum:',
      '<h3>Perfil claro e específico</h3>',
      'Não é "psicólogo". É "psicólogo brasileiro especializado em expatriados em Portugal". Não é "nutricionista". É "nutricionista que ajuda brasileiros a manter hábitos saudáveis no exterior". Especificidade gera confiança.',
      '<h3>Conteúdo consistente</h3>',
      'Um post por semana no Instagram. Um artigo por mês no blog. Uma newsletter quinzenal. Você não precisa estar em todas as redes, mas precisa estar presente de forma previsível.',
      '<h3>Experiência impecável</h3>',
      'Agendamento fácil. Lembrete automático. Videochamada estável. Pagamento simples. Acompanhamento pós-sessão. Cada detalhe que você facilita é um cliente que volta e indica.',
      '<h2>A plataforma como acelerador</h2>',
      'O que levaria meses para construir sozinho — site, pagamento, agenda, videochamada, perfil público, avaliações — a Muuday oferece pronto. Você cria seu perfil, define preços e serviços, e começa a ser encontrado por brasileiros que já estão procurando exatamente o que você oferece.',
      'A Dra. Fernanda começou com zero clientes no exterior. Em três meses, atendia doze brasileiros em três países. Em seis meses, tinha lista de espera. Ela não mudou de profissão. Só mudou de canal.',
      '<h2>O futuro é distribuído</h2>',
      'O modelo de trabalho presencial, 9-17, em um único lugar, está morrendo. O futuro é distribuído, flexível, global. Profissionais brasileiros têm uma vantagem única: entendem uma cultura rica, falam uma língua falada por 260 milhões de pessoas, e podem atender de qualquer lugar do mundo.',
      'A pergunta não é se você consegue. A pergunta é quando você vai começar.',
    ],
  },
]

export function getAllArticles(): BlogArticle[] {
  return BLOG_ARTICLES
}

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return BLOG_ARTICLES.find((a) => a.slug === slug)
}

export function getArticlesByCategory(category: BlogCategory): BlogArticle[] {
  return BLOG_ARTICLES.filter((a) => a.category === category)
}
