// All Stripe-supported currencies
export const STRIPE_CURRENCIES = [
  { value: 'AED', label: 'AED - Dirham dos Emirados Árabes' },
  { value: 'AFN', label: 'AFN - Afghani Afegão' },
  { value: 'ALL', label: 'ALL - Lek Albanês' },
  { value: 'AMD', label: 'AMD - Dram Armênio' },
  { value: 'ANG', label: 'ANG - Florim das Antilhas Holandesas' },
  { value: 'AOA', label: 'AOA - Kwanza Angolano' },
  { value: 'ARS', label: 'ARS - Peso Argentino' },
  { value: 'AUD', label: 'AUD - Dólar Australiano' },
  { value: 'AWG', label: 'AWG - Florim Arubano' },
  { value: 'AZN', label: 'AZN - Manat Azerbaijano' },
  { value: 'BAM', label: 'BAM - Marco da Bósnia e Herzegovina' },
  { value: 'BBD', label: 'BBD - Dólar de Barbados' },
  { value: 'BDT', label: 'BDT - Taka Bangladeshi' },
  { value: 'BGN', label: 'BGN - Lev Búlgaro' },
  { value: 'BIF', label: 'BIF - Franco Burundinês' },
  { value: 'BMD', label: 'BMD - Dólar das Bermudas' },
  { value: 'BND', label: 'BND - Dólar de Brunei' },
  { value: 'BOB', label: 'BOB - Boliviano' },
  { value: 'BRL', label: 'BRL - Real Brasileiro' },
  { value: 'BSD', label: 'BSD - Dólar das Bahamas' },
  { value: 'BWP', label: 'BWP - Pula Botswanesa' },
  { value: 'BYN', label: 'BYN - Rublo Bielorrusso' },
  { value: 'BZD', label: 'BZD - Dólar de Belize' },
  { value: 'CAD', label: 'CAD - Dólar Canadense' },
  { value: 'CDF', label: 'CDF - Franco Congolês' },
  { value: 'CHF', label: 'CHF - Franco Suíço' },
  { value: 'CLP', label: 'CLP - Peso Chileno' },
  { value: 'CNY', label: 'CNY - Yuan Chinês' },
  { value: 'COP', label: 'COP - Peso Colombiano' },
  { value: 'CRC', label: 'CRC - Colón Costa-riquenho' },
  { value: 'CVE', label: 'CVE - Escudo Cabo-verdiano' },
  { value: 'CZK', label: 'CZK - Coroa Tcheca' },
  { value: 'DJF', label: 'DJF - Franco Djiboutiano' },
  { value: 'DKK', label: 'DKK - Coroa Dinamarquesa' },
  { value: 'DOP', label: 'DOP - Peso Dominicano' },
  { value: 'DZD', label: 'DZD - Dinar Argelino' },
  { value: 'EGP', label: 'EGP - Libra Egípcia' },
  { value: 'ETB', label: 'ETB - Birr Etíope' },
  { value: 'EUR', label: 'EUR - Euro' },
  { value: 'FJD', label: 'FJD - Dólar Fijiano' },
  { value: 'FKP', label: 'FKP - Libra das Ilhas Malvinas' },
  { value: 'GBP', label: 'GBP - Libra Esterlina' },
  { value: 'GEL', label: 'GEL - Lari Georgiano' },
  { value: 'GIP', label: 'GIP - Libra de Gibraltar' },
  { value: 'GMD', label: 'GMD - Dalasi Gambiano' },
  { value: 'GNF', label: 'GNF - Franco Guineense' },
  { value: 'GTQ', label: 'GTQ - Quetzal Guatemalteco' },
  { value: 'GYD', label: 'GYD - Dólar Guianês' },
  { value: 'HKD', label: 'HKD - Dólar de Hong Kong' },
  { value: 'HNL', label: 'HNL - Lempira Hondurenho' },
  { value: 'HRK', label: 'HRK - Kuna Croata' },
  { value: 'HTG', label: 'HTG - Gourde Haitiano' },
  { value: 'HUF', label: 'HUF - Forint Húngaro' },
  { value: 'IDR', label: 'IDR - Rupia Indonésia' },
  { value: 'ILS', label: 'ILS - Novo Shekel Israelense' },
  { value: 'INR', label: 'INR - Rupia Indiana' },
  { value: 'ISK', label: 'ISK - Coroa Islandesa' },
  { value: 'JMD', label: 'JMD - Dólar Jamaicano' },
  { value: 'JPY', label: 'JPY - Iene Japonês' },
  { value: 'KES', label: 'KES - Xelim Queniano' },
  { value: 'KGS', label: 'KGS - Som Quirguiz' },
  { value: 'KHR', label: 'KHR - Riel Cambojano' },
  { value: 'KMF', label: 'KMF - Franco Comorense' },
  { value: 'KRW', label: 'KRW - Won Sul-coreano' },
  { value: 'KYD', label: 'KYD - Dólar das Ilhas Cayman' },
  { value: 'KZT', label: 'KZT - Tenge Cazaque' },
  { value: 'LAK', label: 'LAK - Kip Laosiano' },
  { value: 'LBP', label: 'LBP - Libra Libanesa' },
  { value: 'LKR', label: 'LKR - Rupia do Sri Lanka' },
  { value: 'LRD', label: 'LRD - Dólar Liberiano' },
  { value: 'LSL', label: 'LSL - Loti Lesotiano' },
  { value: 'MAD', label: 'MAD - Dirham Marroquino' },
  { value: 'MDL', label: 'MDL - Leu Moldavo' },
  { value: 'MGA', label: 'MGA - Ariary Malgaxe' },
  { value: 'MKD', label: 'MKD - Denar Macedônio' },
  { value: 'MMK', label: 'MMK - Kyat Mianmarês' },
  { value: 'MNT', label: 'MNT - Tugrik Mongol' },
  { value: 'MOP', label: 'MOP - Pataca Macaense' },
  { value: 'MRO', label: 'MRO - Uguia Mauritana' },
  { value: 'MUR', label: 'MUR - Rupia Mauriciana' },
  { value: 'MVR', label: 'MVR - Rufiyaa Maldiviana' },
  { value: 'MWK', label: 'MWK - Kwacha Malauiano' },
  { value: 'MXN', label: 'MXN - Peso Mexicano' },
  { value: 'MYR', label: 'MYR - Ringgit Malaio' },
  { value: 'MZN', label: 'MZN - Metical Moçambicano' },
  { value: 'NAD', label: 'NAD - Dólar Namibiano' },
  { value: 'NGN', label: 'NGN - Naira Nigeriana' },
  { value: 'NIO', label: 'NIO - Córdoba Nicaraguense' },
  { value: 'NOK', label: 'NOK - Coroa Norueguesa' },
  { value: 'NPR', label: 'NPR - Rupia Nepalesa' },
  { value: 'NZD', label: 'NZD - Dólar Neozelandês' },
  { value: 'PAB', label: 'PAB - Balboa Panamenho' },
  { value: 'PEN', label: 'PEN - Sol Peruano' },
  { value: 'PGK', label: 'PGK - Kina Papua-Nova-Guinense' },
  { value: 'PHP', label: 'PHP - Peso Filipino' },
  { value: 'PKR', label: 'PKR - Rupia Paquistanesa' },
  { value: 'PLN', label: 'PLN - Zloty Polonês' },
  { value: 'PYG', label: 'PYG - Guarani Paraguaio' },
  { value: 'QAR', label: 'QAR - Rial Catariano' },
  { value: 'RON', label: 'RON - Leu Romeno' },
  { value: 'RSD', label: 'RSD - Dinar Sérvio' },
  { value: 'RUB', label: 'RUB - Rublo Russo' },
  { value: 'RWF', label: 'RWF - Franco Ruandês' },
  { value: 'SAR', label: 'SAR - Riyal Saudita' },
  { value: 'SBD', label: 'SBD - Dólar das Ilhas Salomão' },
  { value: 'SCR', label: 'SCR - Rupia Seychellense' },
  { value: 'SEK', label: 'SEK - Coroa Sueca' },
  { value: 'SGD', label: 'SGD - Dólar de Singapura' },
  { value: 'SHP', label: 'SHP - Libra de Santa Helena' },
  { value: 'SLL', label: 'SLL - Leone Serra-leonês' },
  { value: 'SOS', label: 'SOS - Xelim Somali' },
  { value: 'SRD', label: 'SRD - Dólar Surinamês' },
  { value: 'STD', label: 'STD - Dobra São-tomense' },
  { value: 'SVC', label: 'SVC - Colón Salvadorenho' },
  { value: 'SZL', label: 'SZL - Lilangeni Suazi' },
  { value: 'THB', label: 'THB - Baht Tailandês' },
  { value: 'TJS', label: 'TJS - Somoni Tadjique' },
  { value: 'TOP', label: 'TOP - Paʻanga Tonganês' },
  { value: 'TRY', label: 'TRY - Lira Turca' },
  { value: 'TTD', label: 'TTD - Dólar de Trinidad e Tobago' },
  { value: 'TWD', label: 'TWD - Novo Dólar Taiwanês' },
  { value: 'TZS', label: 'TZS - Xelim Tanzaniano' },
  { value: 'UAH', label: 'UAH - Hryvnia Ucraniana' },
  { value: 'UGX', label: 'UGX - Xelim Ugandense' },
  { value: 'USD', label: 'USD - Dólar Americano' },
  { value: 'UYU', label: 'UYU - Peso Uruguaio' },
  { value: 'UZS', label: 'UZS - Som Uzbeque' },
  { value: 'VND', label: 'VND - Dong Vietnamita' },
  { value: 'VUV', label: 'VUV - Vatu Vanuatense' },
  { value: 'WST', label: 'WST - Tālā Samoano' },
  { value: 'XAF', label: 'XAF - Franco CFA da África Central' },
  { value: 'XCD', label: 'XCD - Dólar do Caribe Oriental' },
  { value: 'XOF', label: 'XOF - Franco CFA da África Ocidental' },
  { value: 'XPF', label: 'XPF - Franco CFP' },
  { value: 'YER', label: 'YER - Rial Iemenita' },
  { value: 'ZAR', label: 'ZAR - Rand Sul-africano' },
  { value: 'ZMW', label: 'ZMW - Kwacha Zambiano' },
]

// All major IANA timezones
export const ALL_TIMEZONES = [
  // Americas
  { value: 'Pacific/Honolulu', label: 'Honolulu (UTC-10)' },
  { value: 'America/Anchorage', label: 'Anchorage (UTC-9)' },
  { value: 'America/Los_Angeles', label: 'Los Angeles / Vancouver (UTC-8)' },
  { value: 'America/Tijuana', label: 'Tijuana (UTC-8)' },
  { value: 'America/Denver', label: 'Denver / Calgary (UTC-7)' },
  { value: 'America/Phoenix', label: 'Phoenix / Arizona (UTC-7, sem horário de verão)' },
  { value: 'America/Chicago', label: 'Chicago / Winnipeg (UTC-6)' },
  { value: 'America/Mexico_City', label: 'Cidade do México / Monterrey (UTC-6)' },
  { value: 'America/Guatemala', label: 'Guatemala / San José (UTC-6)' },
  { value: 'America/New_York', label: 'Nova York / Toronto (UTC-5)' },
  { value: 'America/Bogota', label: 'Bogotá / Lima / Quito (UTC-5)' },
  { value: 'America/Havana', label: 'Havana (UTC-5)' },
  { value: 'America/Panama', label: 'Panamá (UTC-5)' },
  { value: 'America/Halifax', label: 'Halifax (UTC-4)' },
  { value: 'America/Caracas', label: 'Caracas (UTC-4)' },
  { value: 'America/La_Paz', label: 'La Paz / Manaus (UTC-4)' },
  { value: 'America/Puerto_Rico', label: 'Porto Rico / Santo Domingo (UTC-4)' },
  { value: 'America/Cuiaba', label: 'Cuiabá / Campo Grande (UTC-4)' },
  { value: 'America/St_Johns', label: 'St. Johns / Newfoundland (UTC-3:30)' },
  { value: 'America/Sao_Paulo', label: 'São Paulo / Brasília (UTC-3)' },
  { value: 'America/Fortaleza', label: 'Fortaleza / Recife / Salvador (UTC-3)' },
  { value: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires (UTC-3)' },
  { value: 'America/Montevideo', label: 'Montevidéu (UTC-3)' },
  { value: 'America/Santiago', label: 'Santiago (UTC-3/-4)' },
  { value: 'America/Asuncion', label: 'Assunção (UTC-3/-4)' },
  { value: 'America/Guyana', label: 'Georgetown / Paramaribo (UTC-3)' },
  { value: 'America/Noronha', label: 'Fernando de Noronha (UTC-2)' },
  { value: 'Atlantic/Azores', label: 'Açores (UTC-1)' },
  { value: 'Atlantic/Cape_Verde', label: 'Cabo Verde (UTC-1)' },

  // Europe & Africa (UTC+0)
  { value: 'Europe/London', label: 'Londres / Dublin / Lisboa (UTC+0)' },
  { value: 'Atlantic/Reykjavik', label: 'Reykjavik (UTC+0)' },
  { value: 'Africa/Abidjan', label: 'Abidjan / Dacar / Accra (UTC+0)' },
  { value: 'Africa/Casablanca', label: 'Casablanca (UTC+0/+1)' },

  // Europe (UTC+1)
  { value: 'Europe/Paris', label: 'Paris / Berlim / Roma / Madri (UTC+1)' },
  { value: 'Europe/Amsterdam', label: 'Amsterdã / Bruxelas (UTC+1)' },
  { value: 'Europe/Warsaw', label: 'Varsóvia / Praga / Budapeste (UTC+1)' },
  { value: 'Europe/Stockholm', label: 'Estocolmo / Oslo / Copenhague (UTC+1)' },
  { value: 'Europe/Zurich', label: 'Zurique / Viena (UTC+1)' },
  { value: 'Africa/Lagos', label: 'Lagos / Luanda / Douala (UTC+1)' },
  { value: 'Africa/Algiers', label: 'Argel / Tunis (UTC+1)' },

  // Europe (UTC+2)
  { value: 'Europe/Athens', label: 'Atenas / Helsinque / Riga (UTC+2)' },
  { value: 'Europe/Bucharest', label: 'Bucareste / Sofia / Kiev (UTC+2)' },
  { value: 'Africa/Cairo', label: 'Cairo (UTC+2)' },
  { value: 'Africa/Johannesburg', label: 'Joanesburgo / Harare / Maputo (UTC+2)' },
  { value: 'Asia/Jerusalem', label: 'Jerusalém (UTC+2)' },
  { value: 'Asia/Amman', label: 'Amã / Beirute / Damasco (UTC+2)' },

  // UTC+3
  { value: 'Europe/Istanbul', label: 'Istambul (UTC+3)' },
  { value: 'Europe/Moscow', label: 'Moscou / Minsk (UTC+3)' },
  { value: 'Asia/Riyadh', label: 'Riad / Kuwait / Bagdá (UTC+3)' },
  { value: 'Africa/Nairobi', label: 'Nairóbi / Adis Abeba / Dar es Salaam (UTC+3)' },
  { value: 'Asia/Qatar', label: 'Doha (UTC+3)' },

  // UTC+3:30
  { value: 'Asia/Tehran', label: 'Teerã (UTC+3:30)' },

  // UTC+4
  { value: 'Asia/Dubai', label: 'Dubai / Abu Dhabi (UTC+4)' },
  { value: 'Asia/Baku', label: 'Baku / Tbilisi / Yerevan (UTC+4)' },
  { value: 'Indian/Mauritius', label: 'Maurício / Reunião (UTC+4)' },

  // UTC+4:30
  { value: 'Asia/Kabul', label: 'Cabul (UTC+4:30)' },

  // UTC+5
  { value: 'Asia/Karachi', label: 'Carachi / Tashkent (UTC+5)' },
  { value: 'Asia/Yekaterinburg', label: 'Yekaterinburgo (UTC+5)' },
  { value: 'Indian/Maldives', label: 'Maldivas (UTC+5)' },

  // UTC+5:30
  { value: 'Asia/Kolkata', label: 'Mumbai / Nova Delhi / Kolkata (UTC+5:30)' },
  { value: 'Asia/Colombo', label: 'Colombo (UTC+5:30)' },

  // UTC+5:45
  { value: 'Asia/Kathmandu', label: 'Katmandu (UTC+5:45)' },

  // UTC+6
  { value: 'Asia/Dhaka', label: 'Daca / Almaty (UTC+6)' },

  // UTC+6:30
  { value: 'Asia/Yangon', label: 'Yangon / Mianmar (UTC+6:30)' },

  // UTC+7
  { value: 'Asia/Bangkok', label: 'Bangkok / Hanói / Jacarta (UTC+7)' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh (UTC+7)' },

  // UTC+8
  { value: 'Asia/Shanghai', label: 'Xangai / Pequim / Chongqing (UTC+8)' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong / Macau (UTC+8)' },
  { value: 'Asia/Singapore', label: 'Singapura / Kuala Lumpur (UTC+8)' },
  { value: 'Asia/Taipei', label: 'Taipei (UTC+8)' },
  { value: 'Asia/Manila', label: 'Manila (UTC+8)' },
  { value: 'Australia/Perth', label: 'Perth (UTC+8)' },
  { value: 'Asia/Ulaanbaatar', label: 'Ulã Bator (UTC+8)' },

  // UTC+9
  { value: 'Asia/Tokyo', label: 'Tóquio / Osaka / Seoul (UTC+9)' },
  { value: 'Asia/Seoul', label: 'Seul (UTC+9)' },

  // UTC+9:30
  { value: 'Australia/Darwin', label: 'Darwin (UTC+9:30)' },
  { value: 'Australia/Adelaide', label: 'Adelaide (UTC+9:30/10:30)' },

  // UTC+10
  { value: 'Australia/Sydney', label: 'Sydney / Melbourne / Canberra (UTC+10/11)' },
  { value: 'Australia/Brisbane', label: 'Brisbane (UTC+10, sem horário de verão)' },
  { value: 'Pacific/Port_Moresby', label: 'Port Moresby / Guam (UTC+10)' },

  // UTC+11
  { value: 'Pacific/Noumea', label: 'Noumea / Honiara (UTC+11)' },

  // UTC+12
  { value: 'Pacific/Auckland', label: 'Auckland / Wellington (UTC+12/13)' },
  { value: 'Pacific/Fiji', label: 'Fiji (UTC+12)' },

  // UTC+13
  { value: 'Pacific/Apia', label: "Apia / Nuku'alofa (UTC+13)" },
]
