import type { OnboardingFieldMatrixRow } from './onboarding-gates'

export function buildOnboardingMatrix(
  fieldState: Record<string, boolean>,
  categorySensitive: boolean,
): OnboardingFieldMatrixRow[] {
  return [
    {
      field: 'name',
      required_at_account_creation: true,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.name,
    },
    {
      field: 'email',
      required_at_account_creation: true,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.email,
    },
    {
      field: 'country_of_residence',
      required_at_account_creation: true,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.country_of_residence,
    },
    {
      field: 'timezone',
      required_at_account_creation: true,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.timezone,
    },
    {
      field: 'primary_language',
      required_at_account_creation: true,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.primary_language,
    },
    {
      field: 'display_name',
      required_at_account_creation: false,
      required_for_valid_profile_draft: true,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.display_name,
    },
    {
      field: 'category_subcategory_specialty',
      required_at_account_creation: false,
      required_for_valid_profile_draft: true,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.category_subcategory_specialty,
    },
    {
      field: 'headline_short_bio',
      required_at_account_creation: false,
      required_for_valid_profile_draft: true,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.headline_short_bio,
    },
    {
      field: 'profile_photo',
      required_at_account_creation: false,
      required_for_valid_profile_draft: true,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.profile_photo,
    },
    {
      field: 'credentials_upload',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: categorySensitive,
      required_for_go_live: categorySensitive,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.credentials_upload,
    },
    {
      field: 'at_least_one_service',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.at_least_one_service,
    },
    {
      field: 'service_price_and_duration',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.service_price_and_duration,
    },
    {
      field: 'availability_baseline',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.availability_baseline,
    },
    {
      field: 'acceptance_mode_choice',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.acceptance_mode_choice,
    },
    {
      field: 'cancellation_policy_acceptance',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.cancellation_policy_acceptance,
    },
    {
      field: 'professional_plan_selection',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.professional_plan_selection,
    },
    {
      field: 'terms_acceptance',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.terms_acceptance,
    },
    {
      field: 'billing_card_for_professional_plan',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: false,
      met: fieldState.billing_card_for_professional_plan,
    },
    {
      field: 'payout_connected_account_minimum',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: true,
      required_for_go_live: true,
      required_for_first_booking_acceptance: true,
      required_for_payout: true,
      met: fieldState.payout_connected_account_minimum,
    },
    {
      field: 'payout_kyc_complete',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: true,
      required_for_payout: true,
      met: fieldState.payout_kyc_complete,
    },
    {
      field: 'video_intro_optional',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.video_intro_optional,
    },
    {
      field: 'social_links_optional',
      required_at_account_creation: false,
      required_for_valid_profile_draft: false,
      required_for_review_submission: false,
      required_for_go_live: false,
      required_for_first_booking_acceptance: false,
      required_for_payout: false,
      met: fieldState.social_links_optional,
    },
  ]
}
